baseURL = 'https://spo0q.github.io/ai-layouts/'
languageCode = 'en-us'
title = 'MY LAYOUTS'

disableKinds = ["taxonomy", "RSS", "sitemap"]
enableRobotsTXT = true
enableEmoji = true
canonifyURLs = true

[params]
showDebugBar = true
custom_param = "lol"

[module]
  [module.imports]
  	path = "github.com/spo0q/hugo-debug-bar"
